// BYOND lower-cases color values, and thus we do so as well to ensure atom.color == COLOR_X will work correctly
//some colors
#define COLOR_FOREST_GREEN      "#204f13"
#define COLOR_LUMINOL             "#66FFFF"
#define COLOR_LEATHER "#5C4831"
#define COLOR_WET_LEATHER "#3C2F20"
#define COLOR_DEEP_SKY_BLUE "#00e1ff"
#define COLOR_NAVY_BLUE "#000080"
#define COLOR_DARK_GRAY "#404040"
#define COLOR_PHORON "#FC2BC5"
#define COLOR_PLATINUM "#F4F2FC"
#define COLOR_TRITIUM "#777777"
#define COLOR_LEAD "#273956"
#define COLOR_BROWN_ORANGE "#824b28"
#define COLOR_GRAY40 "#666666"
#define COLOR_SEDONA "#cc6600"
#define COLOR_DENIM "#294665"
#define COLOR_SUN "#ec8b2f"
#define COLOR_GRAY80 "#cccccc"
#define COLOR_NT_RED "#9d2300"
#define COLOR_GUNMETAL "#545c68"
#define COLOR_MUZZLE_FLASH "#ffffb2"
#define COLOR_CHESTNUT "#996633"
#define COLOR_BEASTY_BROWN "#663300"
#define COLOR_WHEAT "#ffff99"
#define COLOR_CYAN_BLUE "#3366cc"
#define COLOR_LIGHT_CYAN "#66ccff"
#define COLOR_PAKISTAN_GREEN "#006600"
#define COLOR_HULL "#436b8e"
#define COLOR_AMBER "#ffbf00"
#define COLOR_COMMAND_BLUE "#46698c"
#define COLOR_SKY_BLUE "#5ca1cc"
#define COLOR_CIVIE_GREEN "#b7f27d"
#define COLOR_TITANIUM "#d1e6e3"
#define COLOR_GOLD "#FFCC4C"

#define COLOR_SANDSTONE "#D9C179"
#define COLOR_MARBLE "#AAAAAA"
#define COLOR_CONCRETE "#727272"
#define COLOR_URANIUM "#007A00"
#define    PIPE_COLOR_GREY "#ffffff"    //yes white is grey
#define    PIPE_COLOR_RED "#ff0000"
#define    PIPE_COLOR_BLUE "#0000ff"
#define    PIPE_COLOR_CYAN "#00ffff"
#define    PIPE_COLOR_GREEN "#00ff00"
#define    PIPE_COLOR_YELLOW "#ffcc00"
#define    PIPE_COLOR_BLACK "#444444"
#define    PIPE_COLOR_ORANGE "#b95a00"
#define    PIPE_COLOR_PURPLE	"#5c1ec0"
#define    COMMS_COLOR_DEFAULT "#ff00ff"
#define    COMMS_COLOR_ENTERTAIN "#666666"
#define    COMMS_COLOR_AI "#ff00ff"
#define    COMMS_COLOR_COMMON "#408010"
#define    COMMS_COLOR_SERVICE "#709b00"
#define    COMMS_COLOR_SUPPLY "#7f6539"
#define    COMMS_COLOR_SCIENCE "#993399"
#define    COMMS_COLOR_MEDICAL "#009190"
#define    COMMS_COLOR_EXPLORER "#929820"
#define    COMMS_COLOR_ENGINEER "#a66300"
#define    COMMS_COLOR_SECURITY "#930000"
#define    COMMS_COLOR_COMMAND "#204090"
#define    COMMS_COLOR_CENTCOMM "#5c5c7c"
#define    COMMS_COLOR_SYNDICATE "#6d3f40"
#define GLASS_COLOR "#74b1ee"
#define GLASS_COLOR_PHORON "#7c3a9a"
#define GLASS_COLOR_TINTED "#222222"
#define GLASS_COLOR_FROSTED "#ffffff"
#define COLOR_BLOOD_HUMAN "#a10808"
#define COLOR_BOTTLE_GREEN "#1f6b4f"
#define COLOR_PALE_BTL_GREEN "#57967f"
#define COLOR_DARK_GUNMETAL "#4c535b"
// Used by fluid system.
#define COLOR_OCEAN "#99f5ff"
//Light color
#define COLOR_LIGHTING_DEFAULT_BRIGHT                    "#999999"
#define COLOR_LIGHTING_DEFAULT_DARK                        "#444444"
#define COLOR_LIGHTING_RED_MACHINERY                    "#dd081b"
#define COLOR_LIGHTING_RED_BRIGHT                        "#aa2733"
#define COLOR_LIGHTING_RED_DARK                            "#6d030c"
#define COLOR_LIGHTING_GREEN_MACHINERY                    "#16ca2c"
#define COLOR_LIGHTING_GREEN_BRIGHT                        "#8aa88a"
#define COLOR_LIGHTING_GREEN_DARK                        "#3a5f3a"
#define COLOR_LIGHTING_BLUE_MACHINERY                    "#162cca"
#define COLOR_LIGHTING_BLUE_BRIGHT                        "#8a95a8"
#define COLOR_LIGHTING_BLUE_DARK                        "#3a4b5f"
#define COLOR_LIGHTING_ORANGE_MACHINERY                    "#e0900b"
#define COLOR_LIGHTING_ORANGE_BRIGHT                    "#d7be93"
#define COLOR_LIGHTING_ORANGE_DARK                        "#684e22"
#define COLOR_LIGHTING_PURPLE_MACHINERY                    "#e614d3"
#define COLOR_LIGHTING_PURPLE_BRIGHT                    "#aa2799"
#define COLOR_LIGHTING_PURPLE_DARK                        "#752f6e"
#define COLOR_LIGHTING_CYAN_MACHINERY                    "#50edd9"
#define COLOR_LIGHTING_CYAN_BRIGHT                        "#67c1b6"
#define COLOR_LIGHTING_CYAN_DARK                        "#28766c"
#define COLOR_LIGHTING_MAINT_DARK                        "#55493f"
#define COLOR_LIGHTING_CREW_SOFT                        "#fef9e7"
#define COLOR_LIGHTING_SCI_BRIGHT                        "#6a6c71"
#define COLOR_LIGHTING_SCI_DARK                            "#4f535f"

#define CODEX_COLOR_ANTAG     "#e5a2a2"

#define COLOR_WEBHOOK_DEFAULT 0x8bbbd5

#define RANDOM_RGB rgb(rand(0,255), rand(0,255), rand(0,255))

// Triadic Palette
#define LIGHT_COLOR_RED        "#FA6496"
#define LIGHT_COLOR_COOPER     "#E69E7F"
#define LIGHT_COLOR_SKYBLUE    "#7DD3FF"

// Neon pallette
#define LIGHT_COLOR_HOTPINK			 "#F419A0"
#define LIGHT_COLOR_NEONGREEN		 "#1FFF0F"
#define LIGHT_COLOR_NEONRED   		 "#f80000"
#define LIGHT_COLOR_NEONYELLOW		 "#FFF01F"
#define LIGHT_COLOR_NEONLIGHTBLUE	 "#7df9ff"
#define LIGHT_COLOR_NEONBLUE		 "#4D4DFF"
#define LIGHT_COLOR_NEONDARKBLUE	 "#000370"
#define LIGHT_COLOR_NEONORANGE		 "#FF5733"
