#define SARATHI_SNOUTED_MASK_PATH 'mod_celadon/_storge_icons/icons/mob/species/mask_snouted.dmi'
#define SARATHI_SNOUTED_HELM_PATH 'mod_celadon/_storge_icons/icons/mob/species/helms_snouted.dmi'
#define SARATHI_DIGITIGRADE_SUIT_PATH 'mod_celadon/_storge_icons/icons/mob/species/digitigrade_suit.dmi'
#define SARATHI_DIGITIGRADE_BOOTS_PATH 'mod_celadon/_storge_icons/icons/mob/species/digitigrade_boots.dmi'
#define SARATHI_DIGITIGRADE_UNDER_PATH 'mod_celadon/_storge_icons/icons/mob/species/digitigrade_under.dmi'
