GLOBAL_LIST_INIT(astroloot, list(
	/obj/item/stack/ore/uranium = 50,
	/obj/item/stack/ore/iron = 50,
	/obj/item/stack/ore/plasma = 75,
	/obj/item/stack/ore/silver = 50,
	/obj/item/stack/ore/gold = 50,
	/obj/item/stack/ore/diamond = 25,
	/obj/item/stack/ore/hellstone = 5,
	/obj/item/stack/ore/titanium = 75,
	/obj/item/pickaxe/diamond = 15,
	/obj/item/borg/upgrade/modkit/cooldown = 5,
	/obj/item/borg/upgrade/modkit/damage = 5,
	/obj/item/borg/upgrade/modkit/range = 5,
	/obj/item/t_scanner/adv_mining_scanner/lesser = 15,
	/obj/item/kinetic_crusher = 15,
	/obj/effect/mob_spawn/human/corpse/damaged/legioninfested = 25,
	/obj/effect/mob_spawn/human/corpse/damaged/legioninfested = 25,
	/obj/effect/mob_spawn/human/corpse/damaged/legioninfested = 25,
	/obj/item/tank/jetpack/suit = 10,
	/obj/item/survivalcapsule = 15,
	/obj/item/reagent_containers/hypospray/medipen/survival = 15,
	/obj/item/gps/mining = 10,
	/obj/item/extraction_pack = 10,
	/obj/item/reagent_containers/food/drinks/beer = 15,
	))
