/obj/structure/closet/crate/freezer/surplus_limbs/PopulateContents()
	. = ..()
	new /obj/item/bodypart/l_arm/robot/surplus/tajara(src)
	new /obj/item/bodypart/r_arm/robot/surplus/tajara(src)
	new /obj/item/bodypart/leg/left/robot/surplus/tajara(src)
	new /obj/item/bodypart/leg/right/robot/surplus/tajara(src)
