name: "Pull Request Labeler"

permissions:
  contents: read

on:
  push:
    branches:
      - beta-dev
  pull_request_target:

jobs:
  triage:
    permissions:
      contents: read # may be required due to overwrite/add ambiguity
      pull-requests: write # required to apply labels to PRs
    runs-on: ubuntu-latest
    steps:
      - name: Check for conflicting PRs
        uses: eps1lon/actions-label-merge-conflict@releases/2.x
        with:
          dirtyLabel: "Merge Conflict"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "Pull Request содержит конфликты. Устраните их, чтобы мы смогли оценить и принять запрос."
      - name: Apply labels based on changed files
        if: github.event_name != 'push'
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.TOKEN || secrets.GITHUB_TOKEN }}"
          sync-labels: true
          configuration-path: .github/labeler.yml
